# Generated by Django 2.0.2 on 2018-03-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was created.')),
                ('last_modified_on', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last modified.')),
                ('summary', models.CharField(help_text='Direct quote or accurate paraphrasing of the claim.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Longer definition of the claim (if needed).')),
                ('context_description', models.CharField(blank=True, help_text='Description of the context in which the claim was made.', max_length=300)),
                ('context_url', models.URLField(blank=True, help_text='Link to the context of the claim (if needed).')),
                ('claimed_on', models.DateField(help_text='Date on which the claim was made.', null=True)),
                ('created_by', models.ForeignKey(help_text='Refers to the user who created the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claim_created', related_query_name='claims_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(help_text='Refers to the user who last modified the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claim_modified', related_query_name='claims_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was created.')),
                ('last_modified_on', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last modified.')),
                ('label', models.CharField(help_text="Label for the rating (e.g., 'True', 'Mostly True').", max_length=20)),
                ('definition', models.CharField(blank=True, help_text='Definition of the rating.', max_length=300)),
                ('image', models.ImageField(blank=True, height_field=100, help_text='Image file representing the rating of the claim.', upload_to='', width_field=100)),
                ('created_by', models.ForeignKey(help_text='Refers to the user who created the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claimrating_created', related_query_name='claimratings_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(help_text='Refers to the user who last modified the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claimrating_modified', related_query_name='claimratings_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rating',
            },
        ),
        migrations.CreateModel(
            name='ClaimReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was created.')),
                ('last_modified_on', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last modified.')),
                ('summary', models.CharField(blank=True, help_text='Short statement summarizing the review of the claim.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Full narrative of the review, including explanations and conclusions surfaced by reporting and research.')),
                ('published_on', models.DateTimeField(help_text='Date and time when the review was/will be published.', null=True)),
                ('claim', models.OneToOneField(help_text='Refers to the claim being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='factchecker.Claim')),
                ('created_by', models.ForeignKey(help_text='Refers to the user who created the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claimreview_created', related_query_name='claimreviews_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(help_text='Refers to the user who last modified the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claimreview_modified', related_query_name='claimreviews_modified', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(help_text='Refers to the rating assigned to the claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='factchecker.ClaimRating')),
            ],
            options={
                'verbose_name': 'review',
            },
        ),
        migrations.CreateModel(
            name='ClaimSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was created.')),
                ('last_modified_on', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last modified.')),
                ('name', models.CharField(help_text="Name of the source of claim (e.g., 'Donald Trump' or the 'National Rifle Association').", max_length=300)),
                ('title', models.CharField(help_text='Title of the source, if it is a person.', max_length=300)),
                ('image', models.ImageField(blank=True, height_field=100, help_text='Image file representing the source.', upload_to='', width_field=100)),
                ('created_by', models.ForeignKey(help_text='Refers to the user who created the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claimsource_created', related_query_name='claimsources_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(help_text='Refers to the user who last modified the object.', on_delete=django.db.models.deletion.PROTECT, related_name='claimsource_modified', related_query_name='claimsources_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'source',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='source',
            field=models.ForeignKey(help_text='Refers to the source of the claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='factchecker.ClaimSource'),
        ),
    ]
