# Generated by Django 2.0.2 on 2018-03-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='last_modified_on',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='claimrating',
            old_name='last_modified_on',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='claimreview',
            old_name='last_modified_on',
            new_name='last_modified_at',
        ),
        migrations.RenameField(
            model_name='claimsource',
            old_name='last_modified_on',
            new_name='last_modified_at',
        ),
    ]
