# Generated by Django 2.0.2 on 2018-03-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0002_auto_20180302_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsource',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the source, if it is a person.', max_length=300),
        ),
    ]
