# Generated by Django 2.0.2 on 2018-03-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0003_auto_20180302_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimed_on',
            field=models.DateField(blank=True, help_text='Date on which the claim was made.', null=True),
        ),
        migrations.AlterField(
            model_name='claimreview',
            name='published_on',
            field=models.DateTimeField(blank=True, help_text='Date and time when the review was/will be published.', null=True),
        ),
        migrations.AlterField(
            model_name='claimreview',
            name='rating',
            field=models.ForeignKey(blank=True, help_text='Refers to the rating assigned to the claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='factchecker.ClaimRating'),
        ),
    ]
