# Generated by Django 2.0.2 on 2018-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0004_auto_20180302_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsource',
            name='source_type',
            field=models.CharField(choices=[('o', 'Organization'), ('p', 'Person')], default='p', help_text="Type of source (e.g., 'Person' or 'Organization').", max_length=1),
            preserve_default=False,
        ),
    ]
