# Generated by Django 2.0.2 on 2018-03-13 16:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0005_claimsource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreview',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full narrative of the review, including explanations and conclusions surfaced by reporting and research.'),
        ),
    ]
