# Generated by Django 2.0.3 on 2018-03-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0006_auto_20180313_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrating',
            name='emojis',
            field=models.CharField(blank=True, help_text='Emojis characters representing the rating of a claim.', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimrating',
            name='image',
            field=models.ImageField(blank=True, height_field=100, help_text='Image file representing the rating of a claim.', upload_to='', width_field=100),
        ),
    ]
