# Generated by Django 2.0.3 on 2018-04-01 03:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0009_auto_20180329_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSubmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Short statement summarizing the review of the claim.', max_length=300)),
                ('email', models.EmailField(blank=True, help_text='Email of claim submitter.', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of claim submitter.', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='claimsource',
            name='source_type',
            field=models.CharField(choices=[('p', 'Person'), ('o', 'Organization')], help_text="Type of source (e.g., 'Person' or 'Organization').", max_length=1),
        ),
        migrations.AddField(
            model_name='claim',
            name='submitter',
            field=models.ForeignKey(help_text='Refers to the person who submitted the claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_submitted', to='factchecker.ClaimSubmitter'),
        ),
    ]
