# Generated by Django 2.0.3 on 2018-04-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0010_auto_20180401_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsubmitter',
            name='name',
            field=models.CharField(help_text='Short statement summarizing the review of the claim.', max_length=300),
        ),
    ]
