# Generated by Django 2.0.3 on 2018-04-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecker', '0012_auto_20180405_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrating',
            name='image',
            field=models.FileField(blank=True, help_text='Image file representing the rating.', upload_to='claim-rating-images/'),
        ),
    ]
